### ISSUE TITLE
Forecasting Task Explanation

### ISSUE THREAD

**Issue by kushal-duetti** [azencot-group/ImagenTime#1]
I'm having a tough time understanding how to train for a conditional generation task. Am I to pass labels which are basically just zeros for the length of the input sequence and 1 for the output sequence? Or do I just run it as currently stated? I must be missing something because it feels like without some sort of mask or whatever, we'd be passing future information in training which you can't do at inference.

**Comment by nimrodberman** [comment]
Thank you for reaching out.

We recently uploaded a new branch called **"conditional"**, which includes the code for conditional generation in the file **"conditional.py"**. You can examine the exact process using debugging mode or by printing the relevant steps. However, we want to note that this branch is not fully tested yet. Once testing is complete, we will merge it into the main branch. In the meantime, you are welcome to use it.

- **During training**, in the extrapolation (forecasting) setting, we have access to future time steps (horizon) to train the model to learn the future distribution conditioned on the past distribution (lookback). This is implemented by applying Gaussian noise only to the future steps while keeping the lookback steps clean.
  
- **During inference**, the model is given only the past (lookback) steps, and it predicts the future steps. This is reflected in our method by initially noising the future steps with Gaussian noise and progressively cleaning them using the information from the unnoised lookback steps.

To conclude, the masks in our method decide which pixel will be clean and which will be noisy.

We hope this explanation clarifies your concerns. If you have any further questions, feel free to ask.

**Comment by kushal-duetti** [comment]
Thank you so much, this makes complete sense, my mistake for not understanding the exact nature of the model architecture. Appreciate it!
